#!/usr/bin/env zsh

set_location() {
  local location="$1"
  echo "${location:-home}" > $HOME/.whereami
  export WHEREAMI=$(wmi)
  chezmoi apply --init
  source ~/.zshrc
}

gohome() {
  set_location "home"
}

gowork() {
  set_location "work"
}

wmi() {
  local wmi=$(<$HOME/.whereami)
  echo "${wmi:-home}"
}

export WHEREAMI=$(wmi)

# SSH Agent
export SSH_AUTH_SOCK=$HOME/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
export EDITOR="nvim"
export SOURCES_ROOT="$HOME/sources"
export GPG_TTY=$(tty)

export PATH="/opt/homebrew/opt/trash/bin:$PATH"
export PATH="$PATH:$SOURCES_ROOT/fin/bin"
export PATH="$PATH:$SOURCES_ROOT/own/fin/bin"
export PATH="$PATH:/usr/local/bin/pulumi"
export PATH="$PATH:/opt/nvim/nvim-macos-x86_64/bin"
export PATH="$PATH:/opt/nvim/nvim-macos-arm64/bin"
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

# asdf
export ASDF_GOLANG_MOD_VERSION_ENABLED=true

