#!/usr/bin/env zsh

# SSH Agent
export SSH_AUTH_SOCK=$HOME/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
export EDITOR="nvim"
export SOURCES_ROOT="$HOME/sources"
export GPG_TTY=$(tty)

export PATH="$PATH:$SOURCES_ROOT/fin/bin"
export PATH="$PATH:$SOURCES_ROOT/own/fin/bin"

# asdf
export ASDF_GOLANG_MOD_VERSION_ENABLED=true


