#!/usr/bin/env zsh

# Attach to an existing tmux session or create a new one
[ -z "$TMUX" ] && exec tmux new -As main

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Load aliases
[ -f ~/.aliasesrc ] && source ~/.aliasesrc
[ -f ~/.private_aliasesrc ] && source ~/.private_aliasesrc

# Load environment variables
[ -f ~/.envrc ] && source ~/.envrc

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# ZSH plugins
source $(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh
source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme
# source $(brew --prefix asdf)/libexec/asdf.sh
source $HOME/.asdf/plugins/golang/set-env.zsh

# Completions folder
mkdir -p $HOME/.zsh_completions
FPATH=$HOME/.zsh_completions:$FPATH

# zsh-completions plugin
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
  FPATH=$SOURCES_ROOT/own/fin/bin:$FPATH
  FPATH=${ASDF_DATA_DIR:-$HOME/.asdf}/completions:$FPATH
  autoload -Uz compinit
  compinit
fi

# History
HISTSIZE=10000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Key bindings for history-substring-search plugin
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down

# Key bindings for zsh-autosuggestions plugin
bindkey '^e' autosuggest-accept  # Accepts the current suggestion.
bindkey '^f' forward-word        # Accepts the next part of the suggestion.

# Completion 
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'  # Case-insensitive tab completion.
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" # Make tab completion colorful.

