return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "delve",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint-lsp",
      "gh",
      "gofumpt",
      "goimports",
      "golangci-lint",
      "gomodifytags",
      "gopls",
      "hadolint",
      "impl",
      "js-debug-adapter",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "shfmt",
      "shfmt",
      "sqlfluff",
      "stylua",
      "stylua",
      "tailwindcss-language-server",
      "taplo",
      "templ",
      "typescript-language-server",
      "vtsls",
      "yaml-language-server",
    },
  },
}
